# Generated by Django 4.2.6 on 2023-10-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('title', models.CharField(max_length=155)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('views', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField()),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=20)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
