# Generated by Django 4.2.6 on 2023-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_alter_youtubevideo_channel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
